name: DEPLOY - FRONTEND

on:
  push:
    branches:
      - '*'
    paths:
      - 'src/backend/'
  pull_request:
    branches:
      - develop

jobs:
  placeholder:
    steps:
      - run: echo "job placeholder"